grpc:
  address: "127.0.0.1" # or domain
  ssl_enable: false
  crt_file: ./server.crt
  key_file: ./server.key
  port: 50001

db: # mongo
  address: ""
  database: ""
  port: 27017
  user: ""
  password: ""

basic:
  store: "/users/tengfei/Documents/source/project/acer/备份/枫迹"

endpoints:
  index: "http://127.0.0.1:13440"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: ""
  secret_access_key: ""
  bucket_name: "whisperingtime"
  use_ssl: false
