web:
  address: "127.0.0.1" # or domain
  ssl_enable: false
  crt_file: ./server.crt
  key_file: ./server.key
  port: 13341

db: # mongo
  address: ""
  database: ""
  port: 27017
  user: ""
  password: ""

basic:
  store: "/users/tengfei/Documents/source/project/acer/备份/枫迹"